#ifndef PINOUT_H
#define PINOUT_H

#define LASER_PIN 15

#define LED_RED_PIN 14
#define LED_GREEN_PIN 12
#define LED_BLUE_PIN 13

#define GPS_SERIAL_TX_PIN 32
#define GPS_SERIAL_RX_PIN 35

#define BUZZER_PIN 2

#define MOTOR_ALTITUDE_DIRECTION_PIN 33
#define MOTOR_ALTITUDE_STEP_PIN 25
#define MOTOR_AZIMUTH_DIRECTION_PIN 26
#define MOTOR_AZIMUTH_STEP_PIN 27

#define PEN_PIN 36
#define SCREEN_BACKLIGHT_PIN 4

#endif
